### ISSUE TITLE
How to open/close the “tracking changes” mode in '*.tex' file？

### ISSUE THREAD

**Issue by deepmeng** [pedromateo/latex_revdiff#5]
open “tracking changes” mode means:  display revision details
close “tracking changes” mode means: don't display revision details, only display the paper in release version

**Comment by pedromateo** [comment]
Hi @deepmeng, I think what you are asking for is here:

%%% package for revision mode
\usepackage[revision]{revdiff}
%\usepackage[clean]{revdiff}

IF you use the clean mode, nothing will be colored and only new statements will be included. Can you try this and if no problem, add this line to README.md file in a way that is useful for you and also for the rest of the people.
Thanks

**Comment by deepmeng** [comment]
@pedromateo many thanks! I submit a pull request to your repository.
