### ISSUE TITLE
Use \color instead of \textcolor

### ISSUE THREAD

**Issue by SecMS** [pedromateo/latex_revdiff#7]
Dear @pedromateo,

I propose to {\color{<color>}...}  instead of \textcolor{<color>}{...} as \textcolor has issues with paragraphs.

Best regards and thanks for your work.

**Comment by pedromateo** [comment]
Hi @SecMS , I totally agree. Please, would you mind to do the change and open a PR choosing me as reviewer.
Thanks for your help!

**Comment by SecMS** [comment]
Hi @pedromateo ,
I forked revdiff and included the changes in my fork and created a pull request.
I hope this is ok for you, too.
Cheers
